name: CI/CD for flask-app
run-name: ${{ github.actor }} is deploying flask-app
on: 
    push:
        branches:
            - main
    workflow_dispatch:
        
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python 3.13
              uses: actions/setup-python@v5
              with:
                  python-version: 3.13

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run tests
              run: |
                  python -m pytest

    docker:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: "Login to Docker Hub"
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push
              id: docker_build
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ vars.DOCKERHUB_USERNAME }}/flask-app:latest
            - name: "image digest"
              run: echo ${{ steps.docker.outputs.digest }}
